### ISSUE TITLE
Correctly Update Player Names

### ISSUE THREAD

**Issue by UnknownPlayer13** [Mirasaki/dayz-leaderboard-bot#22] opened 2022-05-27 15:37 UTC
I have already requested this but sadly it couldnt be implemented.
This is a feature/fix that in my eyes is a important part for the Leaderboard.
Either the leaderboard should update the last names used by players or letting players Change their name via a command /Leaderboard changename (the command part is a bit tricky as im not sure  how we could let only the player update his own name and not those from others.

**Comment by Ariastarcos** [comment] 2022-05-28 14:56
Duplicate of #11 

I'll keep the issue open for now, I'll take another look at the data that is being delivered, see if we can link/track back survivor names to cftools ids

**Comment by Ariastarcos** [comment] 2022-06-07 14:55
using the GET `/v1/server/{server_api_id}/leaderboard` endpoint of the CFTools API returns a list of **survivors**, not CFTools accounts. We could fetch all relevant information for a given player using the `/v1/server/{server_api_id}/player` endpoint, but this is limited to 10 requests per minute, which simply won't do for a bot like this. I am now closing this issue, as this is a CFTools API request, not a bot requests at the moment since I simply can't implement it with the tools available.

**Closed as completed by Ariastarcos** 2022-06-07 14:55 UTC
Labels: bug, duplicate
